"use client";
import { createAppSupabaseClient } from "@/lib/supabaseClient";
import {useEffect,useState} from "react";
import type { Session } from "@supabase/supabase-js";
const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4100/api";const sb=process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?createAppSupabaseClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY):null;
export default function CustomerGallery({id}:{id:string}){const [session,S]=useState<Session|null>(null);const [data,D]=useState<any>(null);const [urls,U]=useState<Record<string,string>>({});const [error,E]=useState("");
useEffect(()=>{let active=true;sb?.auth.getSession().then(({data,error})=>{if(!active)return;if(error){void sb?.auth.signOut();location.replace("/customer/login");return;}if(!data.session){location.replace("/customer/login");return;}if(data.session.user.user_metadata?.user_type==="photographer"||data.session.user.user_metadata?.user_type==="studio"){location.replace("/dashboard");return;}S(data.session);});return()=>{active=false;};},[]);
useEffect(()=>{if(!session)return;fetch(api+"/customer/galleries/"+id,{headers:{Authorization:"Bearer "+session.access_token}}).then(async r=>{const d=await r.json();if(r.status===401){await sb?.auth.signOut();location.replace("/customer/login");return;}if(!r.ok)throw Error(d.error);D(d);for(const m of d.media||[]){const response=await fetch(api+"/customer/galleries/"+id+"/media/"+m.id+"/access",{headers:{Authorization:"Bearer "+session.access_token}});const a=await response.json();if(response.ok)U(v=>({...v,[m.id]:a.type==="video"?a.playbackUrl:a.url}));}}).catch(e=>E(e.message));},[session,id]);
async function download(mediaId:string){if(!session)return;const r=await fetch(api+"/customer/galleries/"+id+"/media/"+mediaId+"/download",{headers:{Authorization:"Bearer "+session.access_token}});const d=await r.json();if(!r.ok){E(d.error||"Could not download this file.");return;}location.assign(d.url);}
return <main className="customer-account"><header className="customer-account-nav"><a href="/customer">← My account</a></header>{error&&<div className="customer-account-state customer-account-error">{error}</div>}{data&&<><section className="customer-account-hero"><p className="directory-eyebrow">{data.gallery.studio} · {data.gallery.project}</p><h1>{data.gallery.title}</h1><p>{data.gallery.description}</p><b>₹{(data.gallery.amountPaid/100).toLocaleString("en-IN")} paid of ₹{(data.gallery.totalAmount/100).toLocaleString("en-IN")}</b>{!data.gallery.downloadsUnlocked&&<p>Downloads unlock after the remaining payment is verified.</p>}</section><section className="customer-media-grid">{data.media.map((m:any)=><article className="customer-media-card" key={m.id}>{!urls[m.id]?<div className="media-loading">Loading preview…</div>:m.mime_type.startsWith("video/")?<iframe src={urls[m.id]} title={m.filename} allow="accelerometer; gyroscope; autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<img src={urls[m.id]} alt={m.filename}/>}<p>{m.filename}</p>{data.gallery.downloadsUnlocked&&<button className="secondary-button" onClick={()=>download(m.id)}>Download original</button>}</article>)}{data.media.length===0&&<div className="customer-account-empty">Your photographer is preparing this gallery.</div>}</section></>}</main>}

