"use client";
import { createAppSupabaseClient } from "@/lib/supabaseClient";
import { useEffect, useState } from "react";
import Script from "next/script";
import { verifyRazorpayCheckout } from "@/lib/payments";
import type { Session } from "@supabase/supabase-js";
const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4100/api";
const sb=process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?createAppSupabaseClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY):null;
type Project={id:string;name:string;status:string;event_date:string|null;total_amount:number;amount_paid:number;organizations?:{name:string}|null;quotations:any[];invoices:any[];galleries:any[]};
declare global{interface Window{Razorpay?:new(options:Record<string,unknown>)=>{open:()=>void;on?:(event:string,handler:(response:any)=>void)=>void}}}
export default function CustomerPortal(){
 const [session,S]=useState<Session|null>(null),[data,D]=useState<any>(null),[error,E]=useState(""),[checkoutReady,setCheckoutReady]=useState(false),[busyQuote,setBusyQuote]=useState<string|null>(null),[quoteMessages,setQuoteMessages]=useState<Record<string,string>>({}),[quoteErrors,setQuoteErrors]=useState<Record<string,string>>({}),[busyBalance,setBusyBalance]=useState<string|null>(null),[balanceMessages,setBalanceMessages]=useState<Record<string,string>>({}),[balanceErrors,setBalanceErrors]=useState<Record<string,string>>({});
 useEffect(()=>{let active=true;void(async()=>{if(!sb){location.replace("/customer/login");return;}const stored=await sb.auth.getSession();let current=stored.error?null:stored.data.session;if(!current){const renewed=await sb.auth.refreshSession();current=renewed.error?null:renewed.data.session;}if(!active)return;if(!current){await sb.auth.signOut();location.replace("/customer/login");return;}if(["photographer","studio"].includes(String(current.user.user_metadata?.user_type).toLowerCase())){location.replace("/dashboard");return;}S(current);})();return()=>{active=false;};},[]);
 async function customerFetch(url:string,init:RequestInit={}){if(!sb)throw Error("Customer sign-in is unavailable.");const stored=await sb.auth.getSession();let current=stored.error?null:stored.data.session;if(!current||current.expires_at&&current.expires_at*1000<Date.now()+45000){const renewed=await sb.auth.refreshSession();current=renewed.error?null:renewed.data.session;}if(!current){await sb.auth.signOut();location.replace("/customer/login");throw Error("Your customer session expired. Sign in again to continue.");}S(previous=>previous?.access_token===current!.access_token?previous:current);const send=(token:string)=>{const headers=new Headers(init.headers);headers.set("Authorization",`Bearer ${token}`);return fetch(url,{...init,headers});};let response=await send(current.access_token);if(response.status===401){const renewed=await sb.auth.refreshSession();if(!renewed.error&&renewed.data.session){current=renewed.data.session;S(current);response=await send(current.access_token);}}if(response.status===401){await sb.auth.signOut();location.replace("/customer/login");}return response;}
 async function refreshAccount(){const response=await customerFetch(api+"/customer/portal");const result=await response.json();if(!response.ok)throw Error(result.error||"Could not refresh your customer account.");D(result);E("");return result;}
 useEffect(()=>{if(!session)return;let active=true,loading=false;const refresh=async()=>{if(loading||document.visibilityState==="hidden")return;loading=true;try{const response=await customerFetch(api+"/customer/portal");const result=await response.json();if(!response.ok)throw Error(result.error);if(active){D(result);E("");}}catch(err){if(active)E(err instanceof Error?err.message:"Could not refresh your customer account.");}finally{loading=false;}};void refresh();const timer=window.setInterval(()=>void refresh(),15000);window.addEventListener("focus",refresh);return()=>{active=false;window.clearInterval(timer);window.removeEventListener("focus",refresh);};},[session]);
 async function logout(){await sb?.auth.signOut();location.replace("/");}
 const cash=(n:number)=>"₹"+(Number(n||0)/100).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
 function quoteMessage(id:string,message:string){setQuoteMessages(v=>({...v,[id]:message}));setQuoteErrors(v=>({...v,[id]:""}));}
 function quoteError(id:string,message:string){setQuoteErrors(v=>({...v,[id]:message}));setQuoteMessages(v=>({...v,[id]:""}));}
 async function acceptQuotation(id:string){if(!session)return;setBusyQuote(id);quoteError(id,"");try{const response=await customerFetch(`${api}/customer/quotations/${id}/accept`,{method:"POST"});const result=await response.json();if(!response.ok)throw Error(result.error||"Could not accept this quotation.");quoteMessage(id,"Quotation accepted. You can now pay the 25% booking advance here.");await refreshAccount();}catch(err){quoteError(id,err instanceof Error?err.message:"Could not accept this quotation.");}finally{setBusyQuote(null);}}
 async function watchAdvance(projectId:string,quoteId:string,total:number){for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,5000));try{const result=await refreshAccount();const item=result?.projects?.find((p:Project)=>p.id===projectId);if(Number(item?.amount_paid)>=Math.round(total*.25)){quoteMessage(quoteId,"Advance payment confirmed. Your booking is updated.");return;}}catch{}}quoteMessage(quoteId,"Payment was submitted and is awaiting confirmation. This page will update when the payment is verified.");}
 async function payAdvance(projectId:string,id:string,total:number,name:string){if(!session)return;setBusyQuote(id);quoteError(id,"");try{const response=await customerFetch(`${api}/customer/quotations/${id}/advance-order`,{method:"POST"});const result=await response.json();if(!response.ok)throw Error(result.error||"Could not start the booking advance.");if(!window.Razorpay)throw Error("Secure checkout is still loading. Please try again in a moment.");const checkout=new window.Razorpay({key:result.keyId,amount:result.amount,currency:result.currency,name:"Photography booking",description:`25% booking advance for ${name}`,order_id:result.orderId,handler:(payload:any)=>{quoteMessage(id,"Payment submitted. Verifying securely…");void(async()=>{try{if(await verifyRazorpayCheckout(payload)){quoteMessage(id,"Advance payment verified. Refreshing your booking…");await refreshAccount();}}catch{}void watchAdvance(projectId,id,total);})();},theme:{color:"#171717"}});checkout.on?.("payment.failed",(payload:any)=>{const detail=payload?.error,reason=detail?.description||detail?.reason||"Razorpay could not complete the payment.";quoteError(id,detail?.code?`${reason} (${detail.code})`:reason);});checkout.open();}catch(err){quoteError(id,err instanceof Error?err.message:"Could not start the booking advance.");}finally{setBusyQuote(null);}}
 function balanceMessage(id:string,message:string){setBalanceMessages(v=>({...v,[id]:message}));setBalanceErrors(v=>({...v,[id]:""}));}
 function balanceError(id:string,message:string){setBalanceErrors(v=>({...v,[id]:message}));setBalanceMessages(v=>({...v,[id]:""}));}
 async function watchBalance(id:string,total:number){for(let i=0;i<12;i++){await new Promise(r=>setTimeout(r,5000));try{const result=await refreshAccount();const item=result?.projects?.find((p:Project)=>p.id===id);if(Number(item?.amount_paid)>=total){balanceMessage(id,"Remaining payment confirmed. Original downloads are now unlocked in the private gallery.");return;}}catch{}}balanceMessage(id,"Payment was submitted and is awaiting confirmation. Downloads unlock after the payment is verified.");}
 async function payBalance(project:Project){if(!session)return;setBusyBalance(project.id);balanceError(project.id,"");try{const response=await customerFetch(`${api}/customer/projects/${project.id}/balance-order`,{method:"POST"});const result=await response.json();if(!response.ok)throw Error(result.error||"Could not start the remaining-balance payment.");if(!window.Razorpay)throw Error("Secure checkout is still loading. Please try again in a moment.");const checkout=new window.Razorpay({key:result.keyId,amount:result.amount,currency:result.currency,name:"Photography booking",description:`Remaining balance for ${project.name}`,order_id:result.orderId,handler:(payload:any)=>{balanceMessage(project.id,"Payment submitted. Verifying securely…");void(async()=>{try{if(await verifyRazorpayCheckout(payload)){balanceMessage(project.id,"Payment verified. Refreshing your booking…");await refreshAccount();}}catch{}void watchBalance(project.id,Number(project.total_amount));})();},theme:{color:"#171717"}});checkout.on?.("payment.failed",(payload:any)=>{const detail=payload?.error,reason=detail?.description||detail?.reason||"Razorpay could not complete the payment.";balanceError(project.id,detail?.code?`${reason} (${detail.code})`:reason);});checkout.open();}catch(err){balanceError(project.id,err instanceof Error?err.message:"Could not start the remaining-balance payment.");}finally{setBusyBalance(null);}}
 const requests=data?.requests||[],projects:Project[]=data?.projects||[],galleryCount=projects.reduce((n,p)=>n+(p.galleries||[]).filter((g:any)=>g.enabled).length,0);
 return <main className="customer-account"><Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="lazyOnload" onReady={()=>setCheckoutReady(true)}/>
  <header className="customer-account-nav"><a className="directory-brand" href="/"><span className="directory-brand-mark">P</span><span>The Photo Gallery<small>CUSTOMER ACCOUNT</small></span></a><div><a href="/photographers">Find a photographer</a><button onClick={logout}>Sign out</button></div></header>
  <div className="customer-dashboard-shell"><section className="customer-account-hero"><div><h1>Your photography, in one place.</h1></div><a className="primary" href="/photographers">Find a photographer <span>→</span></a></section>
   {data&&<section className="customer-account-summary" aria-label="Account summary"><article><span>APPOINTMENT REQUESTS</span><b>{requests.length}</b><small>{requests.length===1?"request":"requests"}</small></article><article><span>PROJECTS</span><b>{projects.length}</b><small>{projects.length===1?"booking":"bookings"}</small></article><article><span>PRIVATE GALLERIES</span><b>{galleryCount}</b><small>{galleryCount===1?"gallery shared":"galleries shared"}</small></article></section>}
   {error&&<div className="customer-account-state customer-account-error" role="alert">{error}</div>}{!data&&!error&&<div className="customer-account-state">Loading your account…</div>}
   {data&&<div className="customer-dashboard-sections"><section className="customer-dashboard-section"><div className="customer-section-title"><div><h2>Requests and updates</h2></div></div>
    {requests.length===0?<div className="customer-account-empty"><div><b>No appointment requests yet</b><p>When you contact a photographer, your request and their response will appear here.</p></div><a href="/photographers">Browse photographers →</a></div>:<div className="customer-request-list">{requests.map((r:any)=><article className="customer-record" key={r.id}><div className="customer-request-main"><span className="customer-status">{String(r.status||"RECEIVED").replaceAll("_"," ")}</span><h3>{r.event_type||"Appointment request"}</h3><p>{r.organizations?.name||"Photographer"}{r.preferred_date?" · "+r.preferred_date:" · Date to be confirmed"}</p></div><span className="customer-request-update">{r.status==="ACCEPTED"?"Your photographer accepted this request.":r.status==="DECLINED"?"The studio could not take this request.":r.status==="CONVERTED"?"This request has been added to your projects.":"Waiting for the studio to respond."}</span></article>)}</div>}
   </section><section className="customer-dashboard-section"><div className="customer-section-title"><div><h2>Projects</h2></div></div>
    {projects.length===0?<div className="customer-account-empty"><div><b>Your projects will appear here</b><p>When a photographer accepts your request or shares a booking, you’ll find its quotation, payments and gallery here.</p></div><a href="/photographers">Browse photographers →</a></div>:<div className="customer-project-list">{projects.map((p:Project)=>{const remaining=Math.max(0,Number(p.total_amount)-Number(p.amount_paid));const progress=p.total_amount>0?Math.min(100,Math.round(Number(p.amount_paid)/Number(p.total_amount)*100)):0;const active=(p.galleries||[]).filter((g:any)=>g.enabled);const quotations=[...(p.quotations||[])].sort((a:any,b:any)=>String(b.created_at||"").localeCompare(String(a.created_at||"")));const acceptedQuotation=quotations.find((q:any)=>q.status==="ACCEPTED");const pendingQuotation=acceptedQuotation?undefined:quotations.find((q:any)=>q.status==="SENT"||q.status==="VIEWED");const currentQuotations=quotations.filter((q:any)=>q.id===acceptedQuotation?.id||q.id===pendingQuotation?.id);const previousQuotations=quotations.filter((q:any)=>!currentQuotations.some((current:any)=>current.id===q.id));const advanceTotal=acceptedQuotation?Math.round(Number(acceptedQuotation.total)*.25):0;const advanceRemaining=Math.max(0,advanceTotal-Number(p.amount_paid));const canPayBalance=remaining>0&&(acceptedQuotation?advanceRemaining===0:Number(p.amount_paid)>0);return <article className="customer-project" key={p.id}>
     <header className="customer-project-heading"><div><span className="customer-status">{String(p.status||"BOOKED").replaceAll("_"," ")}</span><h3>{p.name}</h3><p>{p.organizations?.name||"Photography studio"}{p.event_date?" · "+p.event_date:""}</p></div><div className="customer-total"><small>PROJECT TOTAL</small><b>{cash(p.total_amount)}</b></div></header>
     <div className="customer-payment-overview"><div><span>Paid</span><b>{cash(p.amount_paid)}</b></div><div><span>Remaining</span><b>{cash(remaining)}</b></div><div className="customer-payment-progress" role="progressbar" aria-label="Project payment progress" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${progress}%`}}/></div><small>{progress}% paid</small></div>
     <div className="customer-project-grid"><section className="customer-project-subsection"><h4>Quotations</h4>{quotations.length?<><div className="customer-current-quotations">{currentQuotations.map((q:any)=>{const isPending=q.id===pendingQuotation?.id;return <details className="customer-doc" id={"quotation-"+q.id} key={q.id} open={isPending}><summary><span>{q.number}<small>{String(q.status).replaceAll("_"," ")}</small></span><b>{cash(q.total)}</b></summary><div className="customer-quotation-detail">{(q.line_items||[]).map((l:any,i:number)=><p key={i}>{l.description}<span>{cash((l.quantity||0)*(l.unitAmount||0))}</span></p>)}{q.terms&&<p>{q.terms}</p>}{isPending?<button className="primary" disabled={busyQuote===q.id} onClick={()=>void acceptQuotation(q.id)}>{busyQuote===q.id?"Accepting…":"Accept quotation"}</button>:null}{quoteMessages[q.id]&&<p className="notice" role="status">{quoteMessages[q.id]}</p>}{quoteErrors[q.id]&&<p className="customer-account-state customer-account-error" role="alert">{quoteErrors[q.id]}</p>}</div></details>})}</div>{previousQuotations.length>0&&<details className="customer-doc-history"><summary>Previous quotations <span>{previousQuotations.length}</span></summary><div>{previousQuotations.map((q:any)=><div className="customer-doc-history-row" key={q.id}><span>{q.number}<small>{String(q.status).replaceAll("_"," ")}</small></span><b>{cash(q.total)}</b></div>)}</div></details>}</>:<p className="customer-muted">No quotation shared yet.</p>}</section>
      <section className="customer-project-subsection">
       <h4>Payments and invoices</h4>
       {acceptedQuotation&&advanceRemaining>0&&<div className="customer-advance-action"><div><b>Booking advance</b><p>25% advance · {cash(advanceTotal)} total</p></div><div className="customer-advance-pay"><span>{cash(advanceRemaining)} due now</span><button className="primary" disabled={busyQuote===acceptedQuotation.id||!checkoutReady} onClick={()=>void payAdvance(p.id,acceptedQuotation.id,Number(acceptedQuotation.total),p.name)}>{busyQuote===acceptedQuotation.id?"Preparing payment…":checkoutReady?`Pay booking advance · ${cash(advanceRemaining)}`:"Loading secure checkout…"}</button></div>{quoteMessages[acceptedQuotation.id]&&<p className="notice" role="status">{quoteMessages[acceptedQuotation.id]}</p>}{quoteErrors[acceptedQuotation.id]&&<p className="customer-account-state customer-account-error" role="alert">{quoteErrors[acceptedQuotation.id]}</p>}</div>}
       {!acceptedQuotation&&pendingQuotation&&<div className="customer-advance-action customer-advance-pending"><div><b>Booking advance</b><p>Accept the quotation to unlock its 25% booking advance.</p></div><a href={"#quotation-"+pendingQuotation.id}>Review and accept quotation ↓</a></div>}
       {p.invoices?.length?p.invoices.map((i:any)=><div className="customer-doc-line" key={i.id}><span>{i.number}<small>{i.kind} · {i.status}</small></span><b>{cash(i.amount_paid)} / {cash(i.total)}</b></div>):<p className="customer-muted">No invoice shared yet.</p>}
       {canPayBalance&&<div className="customer-balance-action"><p><span>Remaining balance</span><b>{cash(remaining)}</b></p><button className="primary" disabled={busyBalance===p.id||!checkoutReady} onClick={()=>void payBalance(p)}>{busyBalance===p.id?"Preparing payment…":checkoutReady?"Pay remaining balance":"Loading secure checkout…"}</button>{balanceMessages[p.id]&&<p className="notice" role="status">{balanceMessages[p.id]}</p>}{balanceErrors[p.id]&&<p className="customer-account-state customer-account-error" role="alert">{balanceErrors[p.id]}</p>}</div>}
      </section></div>
      <section className="customer-galleries"><div><h4>Private galleries</h4></div>{active.length?active.map((g:any)=><a className="customer-gallery-link" href={"/customer/gallery/"+g.id} key={g.id}><span><b>{g.title}</b><small>Private project gallery</small></span><strong>Open gallery →</strong></a>):<p className="customer-muted">Your photographer has not shared a gallery yet.</p>}</section>
     </article>})}</div>}
   </section></div>}
   </div>
 </main>;
}
