"use client";
import { createAppSupabaseClient } from "@/lib/supabaseClient";
import { useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4100/api";
const supabase=process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY?createAppSupabaseClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY):null;
type Studio={id:string;name:string};type Project={id:string;name:string};type Media={id:string;filename:string;mime_type:string;file_size_bytes:number};type Gallery={id:string;title:string;enabled:boolean;media:Media[]};
export default function GalleryDesk({initialProjectId="",initialMediaId=""}:{initialProjectId?:string;initialMediaId?:string}){
 const [session,setSession]=useState<Session|null>(null);const [studios,setStudios]=useState<Studio[]>([]);const [org,setOrg]=useState("");const [projects,setProjects]=useState<Project[]>([]);const [project,setProject]=useState("");const [media,setMedia]=useState<Media[]>([]);const [galleries,setGalleries]=useState<Gallery[]>([]);const [selected,setSelected]=useState<string[]>([]);const [selectedByGallery,setSelectedByGallery]=useState<Record<string,string[]>>({});const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{supabase?.auth.getSession().then(({data})=>setSession(data.session));const sub=supabase?.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub?.data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(!session)return;fetch(`${api}/studios`,{headers:{Authorization:`Bearer ${session.access_token}`}}).then(r=>r.json()).then(d=>{setStudios(d.studios||[]);const saved=localStorage.getItem("activeOrganizationId");const chosen=d.studios?.find((studio:Studio)=>studio.id===saved)||((d.studios?.length===1)?d.studios[0]:null);if(chosen)setOrg(chosen.id);}).catch(()=>setError("Could not load your studios."));},[session]);
 useEffect(()=>{if(!session||!org)return;fetch(`${api}/projects`,{headers:{Authorization:`Bearer ${session.access_token}`,"x-organization-id":org}}).then(r=>r.json()).then(d=>{if(d.error)throw Error(d.error);const available:Project[]=d.projects||[];setProjects(available);const preferred=available.find(p=>p.id===initialProjectId);if(preferred)setProject(preferred.id);else if(available.length===1)setProject(available[0].id);}).catch(e=>setError(e.message));},[session,org,initialProjectId]);
 async function refreshProjectData(){if(!session||!org||!project)return;const headers={Authorization:`Bearer ${session.access_token}`,"x-organization-id":org};const [assetsResponse,galleriesResponse]=await Promise.all([fetch(`${api}/gallery-assets/${project}`,{headers}),fetch(`${api}/projects/${project}/galleries`,{headers})]);const [assetsData,galleriesData]=await Promise.all([assetsResponse.json(),galleriesResponse.json()]);if(!assetsResponse.ok)throw Error(assetsData.error||"Could not load project photos.");if(!galleriesResponse.ok)throw Error(galleriesData.error||"Could not load project galleries.");setMedia(assetsData.media||[]);setGalleries(galleriesData.galleries||[]);setSelectedByGallery({});}
 useEffect(()=>{if(!session||!org||!project)return;void refreshProjectData().catch(e=>setError(e.message));},[session,org,project]);
 useEffect(()=>{if(!initialMediaId||!media.some(item=>item.id===initialMediaId))return;setSelected(current=>current.includes(initialMediaId)?current:[...current,initialMediaId]);setSelectedByGallery(current=>Object.fromEntries(galleries.map(g=>[g.id,(current[g.id]||[]).includes(initialMediaId)?current[g.id]:[...(current[g.id]||[]),initialMediaId]])));},[initialMediaId,media,galleries]);
 useEffect(()=>{if(!project||title.trim())return;const name=projects.find(item=>item.id===project)?.name;if(name)setTitle(`${name} gallery`.slice(0,120));},[project,projects,title]);
 async function signIn(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);}
 async function create(e:React.FormEvent){e.preventDefault();if(!session||!org||!project)return;setBusy(true);setError("");try{const headers={Authorization:`Bearer ${session.access_token}`,"x-organization-id":org,"Content-Type":"application/json"};const created=await fetch(`${api}/galleries`,{method:"POST",headers,body:JSON.stringify({projectId:project,title,description})});const result=await created.json();if(!created.ok)throw Error(result.error||"Could not create the gallery.");if(selected.length){const attached=await fetch(`${api}/galleries/${result.gallery.id}/attach`,{method:"POST",headers,body:JSON.stringify({mediaIds:selected})});const attachedResult=await attached.json();if(!attached.ok)throw Error(attachedResult.error||"Gallery created, but selected media could not be attached.");}
 const token=String(result.customerLink).split("/").pop()||"";await fetch(`${api}/projects/${project}/customer-invitation`,{method:"POST",headers,body:JSON.stringify({galleryId:result.gallery.id,galleryToken:token})});setTitle("");setDescription("");setSelected([]);await refreshProjectData();
 }catch(e){setError(e instanceof Error?e.message:"Could not prepare the gallery.");}finally{setBusy(false);}}
 async function addToGallery(galleryId:string){const mediaIds=selectedByGallery[galleryId]||[];if(!session||!org||!mediaIds.length)return;setBusy(true);setError("");try{const response=await fetch(`${api}/galleries/${galleryId}/attach`,{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"x-organization-id":org,"Content-Type":"application/json"},body:JSON.stringify({mediaIds})});const result=await response.json();if(!response.ok)throw Error(result.error||"Could not add these photos.");await refreshProjectData();}catch(e){setError(e instanceof Error?e.message:"Could not add these photos.");}finally{setBusy(false);}}
 async function removeFromGallery(galleryId:string,mediaId:string){if(!session||!org)return;setBusy(true);setError("");try{const response=await fetch(`${api}/galleries/${galleryId}/detach`,{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"x-organization-id":org,"Content-Type":"application/json"},body:JSON.stringify({mediaIds:[mediaId]})});const result=await response.json();if(!response.ok)throw Error(result.error||"Could not remove this photo from the gallery.");await refreshProjectData();}catch(e){setError(e instanceof Error?e.message:"Could not remove this photo from the gallery.");}finally{setBusy(false);}}
 return <section className="panel gallery-desk">{!session?<><div><h2>Prepare a private gallery</h2><p>Sign in to share selected project media with your customer.</p></div><form className="connect-form" onSubmit={signIn}><input type="email" required placeholder="Studio email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary">Sign in</button></form>{error&&<p className="connect-error">{error}</p>}</>:<><div><h2>Create a private client gallery</h2><p>Customers receive a registration email with access to this private gallery. Downloads stay locked until the project balance is paid.</p></div><form className="quotation-form" onSubmit={create}><label>Studio<select required value={org} onChange={e=>setOrg(e.target.value)}><option value="">Select studio</option>{studios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Project<select required value={project} onChange={e=>setProject(e.target.value)}><option value="">Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Gallery title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Wedding highlights"/></label><label>Note for your customer<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="A note to introduce the gallery"/></label>{media.length>0&&<div className="asset-picker"><b>Choose ready media for this new gallery</b>{media.map(m=><label key={m.id}><input type="checkbox" checked={selected.includes(m.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,m.id]:v.filter(id=>id!==m.id))}/><span>{m.mime_type.startsWith("video/")?"▶":"▧"}</span>{m.filename}</label>)}</div>}{error&&<p className="connect-error">{error}</p>}<button className="primary" disabled={!org||!project||busy}>{busy?"Preparing gallery…":selected.length?"Create gallery and share selected photos":"Create gallery and invite customer"}</button></form>
 {project&&<section className="gallery-manage"><div><h2>Manage existing galleries</h2><p>Add uploaded photos and videos to a gallery, or remove media from the gallery. Removed files stay in Storage.</p></div>{galleries.length===0?<p className="gallery-manage-empty">No galleries for this project yet.</p>:galleries.map(g=><article className="gallery-manage-card" key={g.id}><div className="gallery-manage-heading"><div><b>{g.title}</b><small>{g.enabled?"Customer gallery active":"Gallery disabled"} · {g.media.length} item{g.media.length===1?"":"s"}</small></div></div>{g.media.length>0?<div className="gallery-managed-items">{g.media.map(item=><div key={item.id}><span>{item.mime_type.startsWith("video/")?"▶":"▧"} {item.filename}</span><button type="button" className="text-button" disabled={busy} onClick={()=>void removeFromGallery(g.id,item.id)}>Remove from gallery</button></div>)}</div>:<p className="gallery-manage-empty">No media in this gallery yet.</p>}{media.length>0&&<><div className="asset-picker"><b>Choose uploaded media to add</b>{media.map(m=><label key={m.id}><input type="checkbox" checked={(selectedByGallery[g.id]||[]).includes(m.id)} onChange={e=>setSelectedByGallery(v=>({...v,[g.id]:e.target.checked?[...(v[g.id]||[]),m.id]:(v[g.id]||[]).filter(id=>id!==m.id)}))}/><span>{m.mime_type.startsWith("video/")?"▶":"▧"}</span>{m.filename}</label>)}</div><button type="button" className="primary" disabled={busy||!(selectedByGallery[g.id]||[]).length} onClick={()=>void addToGallery(g.id)}>{busy?"Saving…":"Add selected media"}</button></>}</article>)}</section>}
 {error&&<p className="connect-error">{error}</p>}</>}</section>
}
