"use client";
import { createAppSupabaseClient } from "@/lib/supabaseClient";
import { useEffect,useState } from "react";
import type { Session } from "@supabase/supabase-js";
const api=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4100/api";const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const anon=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
type Studio={id:string;name:string;status:string};type Client={id:string;name:string;email:string;phone:string;address:string;notes:string;projectCount:number};type Project={id:string;name:string;status:string;event_type:string;event_date:string|null;location:string;total_amount:number;amount_paid:number;clients:{id:string;name:string;email:string}|null};
export default function ProjectClientDesk({mode}:{mode:"Projects"|"Clients"}){const [supabase]=useState(()=>url&&anon?createAppSupabaseClient(url,anon):null);const [session,setSession]=useState<Session|null>(null);const [studios,setStudios]=useState<Studio[]>([]);const [org,setOrg]=useState("");const [projects,setProjects]=useState<Project[]>([]);const [clients,setClients]=useState<Client[]>([]);const [search,setSearch]=useState("");const [loading,setLoading]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [projectName,setProjectName]=useState("");const [clientChoice,setClientChoice]=useState("new");const [clientName,setClientName]=useState("");const [clientEmail,setClientEmail]=useState("");const [phone,setPhone]=useState("");const [address,setAddress]=useState("");const [notes,setNotes]=useState("");const [eventType,setEventType]=useState("");const [eventDate,setEventDate]=useState("");const [location,setLocation]=useState("");
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe();},[supabase]);
 useEffect(()=>{if(!session)return;fetch(`${api}/studios`,{headers:{Authorization:`Bearer ${session.access_token}`}}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||"Could not load studio access.");const list=d.studios||[];setStudios(list);if(list.length===1)setOrg(list[0].id);}).catch(e=>setError(e.message));},[session]);
 useEffect(()=>{if(org)localStorage.setItem("activeOrganizationId",org);},[org]);
 async function load(){if(!session||!org)return;setLoading(true);setError("");const h={Authorization:`Bearer ${session.access_token}`,"x-organization-id":org};try{const [p,c]=await Promise.all([fetch(`${api}/projects`,{headers:h}),fetch(`${api}/clients`,{headers:h})]);const pd=await p.json(),cd=await c.json();if(!p.ok)throw Error(pd.error||"Could not load projects.");if(!c.ok)throw Error(cd.error||"Could not load clients.");setProjects(pd.projects||[]);setClients(cd.clients||[]);}catch(e){setError(e instanceof Error?e.message:"Could not load records.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[session,org,mode]);
 async function signIn(e:React.FormEvent){e.preventDefault();if(!supabase)return;const {error}=await supabase.auth.signInWithPassword({email:loginEmail,password:loginPassword});if(error)setError(error.message);}const [loginEmail,setLoginEmail]=useState("");const [loginPassword,setLoginPassword]=useState("");
 async function submit(e:React.FormEvent){e.preventDefault();if(!session||!org)return;setBusy(true);setError("");setSuccess("");const body=mode==="Projects"?{name:projectName,...(clientChoice==="new"?{clientName,clientEmail}:{clientId:clientChoice}),eventType,eventDate:eventDate||undefined,location}:{name:clientName,email:clientEmail,phone,address,notes};try{const r=await fetch(`${api}/${mode.toLowerCase()}`,{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`,"x-organization-id":org,"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||"Could not save this record.");if(mode==="Projects"){setProjects(p=>[d.project,...p]);setProjectName("");setClientName("");setClientEmail("");setEventType("");setEventDate("");setLocation("");if(clientChoice==="new"&&d.project.clients)setClients(c=>[{...d.project.clients,phone:"",address:"",notes:"",projectCount:1},...c]);}else{setClients(c=>[d.client,...c]);setClientName("");setClientEmail("");setPhone("");setAddress("");setNotes("");}setSuccess(mode==="Projects"?"Project created.":"Client added.");}catch(e){setError(e instanceof Error?e.message:"Could not save this record.");}finally{setBusy(false);}}
 if(!url||!anon)return <section className="panel records-desk"><h2>{mode}</h2><p>Configure Supabase in <code>apps/web/.env.local</code> before using the workspace.</p></section>;
 if(!session)return <section className="panel records-desk"><div><h2>{mode}</h2><p>Sign in to manage this studio workspace.</p></div><form className="connect-form" onSubmit={signIn}><input type="email" required placeholder="Email address" value={loginEmail} onChange={e=>setLoginEmail(e.target.value)}/><input type="password" required placeholder="Password" value={loginPassword} onChange={e=>setLoginPassword(e.target.value)}/><button className="primary">Sign in</button>{error&&<p className="connect-error">{error}</p>}<a href="/reset-password">Forgot password?</a></form></section>;
 const q=search.trim().toLowerCase();const filteredProjects=projects.filter(p=>[p.name,p.clients?.name,p.event_type,p.status].some(v=>v?.toLowerCase().includes(q)));const filteredClients=clients.filter(c=>[c.name,c.email,c.phone].some(v=>v?.toLowerCase().includes(q)));
 return <section className="records-desk"><div className="records-toolbar"><label>Studio<select value={org} onChange={e=>setOrg(e.target.value)}><option value="">Choose studio</option>{studios.map(st=><option key={st.id} value={st.id}>{st.name} · {st.status.replaceAll("_"," ")}</option>)}</select></label></div>
 {!studios.length&&<div className="panel records-empty">No studio workspace is linked to this account. Create one from the Storage page.</div>}
 {org&&<form className="panel records-create" onSubmit={submit}><h3>{mode==="Projects"?"Create a project":"Add a client"}</h3><div className="records-form-grid">{mode==="Projects"&&<label>Project name<input required minLength={2} value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="Wedding photography"/></label>}{mode==="Projects"&&<label>Client<select required value={clientChoice} onChange={e=>setClientChoice(e.target.value)}><option value="new">Create a new client</option>{clients.map(c=><option value={c.id} key={c.id}>{c.name}{c.email?` · ${c.email}`:""}</option>)}</select></label>}<label>{mode==="Projects"?"Client name":"Client name"}<input required minLength={2} disabled={mode==="Projects"&&clientChoice!=="new"} value={clientName} onChange={e=>setClientName(e.target.value)} placeholder="Full name"/></label><label>Email<input type="email" disabled={mode==="Projects"&&clientChoice!=="new"} value={clientEmail} onChange={e=>setClientEmail(e.target.value)} placeholder="name@example.com"/></label>{mode==="Projects"?<><label>Event type<input value={eventType} onChange={e=>setEventType(e.target.value)} placeholder="Wedding, portrait…"/></label><label>Event date<input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Venue or city"/></label></>:<><label>Phone<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Contact number"/></label><label>Address<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Postal address"/></label><label>Notes<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Private studio notes"/></label></>}</div>{error&&<p className="connect-error">{error}</p>}{success&&<p className="records-success">{success}</p>}<button className="primary" disabled={busy||!org}>{busy?"Saving…":mode==="Projects"?"Create project":"Add client"}</button></form>}
 {org&&<div className="panel records-list"><div className="records-list-header"><h3>{mode==="Projects"?"All projects":"All clients"}</h3><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${mode.toLowerCase()}…`}/></div>{loading?<p>Loading {mode.toLowerCase()}…</p>:mode==="Projects"?filteredProjects.length?<div className="records-table-wrap"><table><thead><tr><th>PROJECT</th><th>CLIENT</th><th>EVENT</th><th>VALUE</th><th>STATUS</th></tr></thead><tbody>{filteredProjects.map(p=><tr key={p.id}><td><a href={`/projects/${p.id}`}><b>{p.name}</b></a></td><td>{p.clients?.name||"—"}<small>{p.clients?.email||""}</small></td><td>{p.event_type||"—"}{p.event_date&&<small>{new Date(`${p.event_date}T00:00:00`).toLocaleDateString()}</small>}</td><td>₹{(Number(p.total_amount||0)/100).toLocaleString("en-IN")}</td><td><span className="status status-blue"><i/>{p.status.replaceAll("_"," ")}</span></td></tr>)}</tbody></table></div>:<p>{q?"No projects match your search.":"No projects yet. Create your first project above."}</p>:filteredClients.length?filteredClients.map(c=><a className="record-row record-link" key={c.id} href={`/clients/${c.id}`}><div><b>{c.name}</b><small>{[c.email,c.phone].filter(Boolean).join(" · ")||"No contact details"}</small></div><span>{c.projectCount} {c.projectCount===1?"project":"projects"} →</span></a>):<p>{q?"No clients match your search.":"No clients yet. Add your first client above."}</p>}</div>}</section>;
}