"use client";
import { createAppSupabaseClient } from "@/lib/supabaseClient";
import { useEffect, useState } from "react";
import type { Session } from "@supabase/supabase-js";
const api = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4100/api";
const supabase = process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ? createAppSupabaseClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) : null;
type Studio = { id:string; name:string; status:string; created_at:string; review_note:string; organization_members:{user_id:string;role:string}[] };
type Organization = { id:string; name:string; status:string; created_at:string; storage_limit_bytes:number; storage_used_bytes:number; storage_reserved_bytes:number; subscription:{plan_name:string;status:string;current_period_end:string|null}; storageAddons:{bytes:number;amount:number;count:number} };

type Overview={summary:{studios:number;customers:number;projects:number;payments:number;capturedPayments:number};projects:any[];customers:any[];payments:any[];subscriptions:any[];health:{api:string;database:string}};
function bytes(n:number){if(n<1024**3)return `${(n/1024**2).toFixed(0)} MB`;if(n<1024**4)return `${(n/1024**3).toFixed(1)} GB`;return `${(n/1024**4).toFixed(2)} TB`;}
function money(n:number){return `₹${(Number(n||0)/100).toLocaleString("en-IN")}`;}
export default function AdminPage(){
 const [session,setSession]=useState<Session|null>(null);const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [studios,setStudios]=useState<Studio[]>([]);const [organizations,setOrganizations]=useState<Organization[]>([]);const [overview,setOverview]=useState<Overview|null>(null);const [limits,setLimits]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);const [busy,setBusy]=useState("");const [storageAddonsAvailable,setStorageAddonsAvailable]=useState(true);const [activeSection,setActiveSection]=useState<"overview"|"studio-approvals"|"studio-accounts">("overview");
 useEffect(()=>{supabase?.auth.getSession().then(({data})=>setSession(data.session));const sub=supabase?.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub?.data.subscription.unsubscribe();},[]); useEffect(()=>{const selectSection=()=>{const hash=window.location.hash.slice(1);if(hash==="studio-approvals"||hash==="studio-accounts"||hash==="overview")setActiveSection(hash);};selectSection();window.addEventListener("hashchange",selectSection);return()=>window.removeEventListener("hashchange",selectSection);},[]);
 async function load(){if(!session)return;setLoading(true);setError("");try{const h={Authorization:`Bearer ${session.access_token}`};const [a,b,c]=await Promise.all([fetch(`${api}/admin/studios`,{headers:h}),fetch(`${api}/admin/organizations`,{headers:h}),fetch(`${api}/admin/overview`,{headers:h})]);const ad=await a.json(),bd=await b.json(),cd=await c.json();if([a,b,c].some(response=>response.status===401)){setStudios([]);setOrganizations([]);setOverview(null);setError("Your admin session expired. Sign in again.");await supabase?.auth.signOut();setSession(null);return;}if(!a.ok)throw Error(ad.error||"Could not load studio approvals.");if(!b.ok)throw Error(bd.error||"Could not load studio operations.");if(!c.ok)throw Error(cd.error||"Could not load the platform overview.");setStudios(ad.studios||[]);setOrganizations(bd.organizations||[]);setStorageAddonsAvailable(bd.storageAddonsAvailable!==false);setOverview(cd);setLimits(Object.fromEntries((bd.organizations||[]).map((o:Organization)=>[o.id,String(Math.floor(o.storage_limit_bytes/1024**3))])));}catch(e){setError(e instanceof Error?e.message:"Could not load admin data.");}finally{setLoading(false);}}
 useEffect(()=>{if(session)void load();},[session]);
 async function signIn(e:React.FormEvent){e.preventDefault();setError("");if(!supabase){setError("Supabase configuration is required.");return;}const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else setPassword("");}
 async function decision(id:string,decision:"APPROVE"|"REJECT") {
   setError("");
   const response=await fetch(api+"/admin/studios/"+encodeURIComponent(id)+"/decision",{method:"POST",headers:{Authorization:"Bearer "+session?.access_token,"Content-Type":"application/json"},body:JSON.stringify({decision})});
   const result=await response.json();
   if(!response.ok){setError(result.error||"Could not update studio approval.");return;}
   setMessage((result.studio.name||"Studio")+(decision==="APPROVE"?" approved.":" declined."));
   await load();
 }
 async function updateStudio(o:Organization,patch:{storageLimitBytes?:number;status?:string}){if(!session)return;setBusy(o.id);setError("");try{const r=await fetch(`${api}/admin/organizations/${o.id}`,{method:"PATCH",headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(patch)});const d=await r.json();if(!r.ok)throw Error(d.error||"Could not update studio.");setMessage(`${o.name} updated.`);await load();}catch(e){setError(e instanceof Error?e.message:"Could not update studio.");}finally{setBusy("");}}
 return <main className="admin-page"><header className="public-header"><a href="/" className="brand"><span className="brand-mark">P</span><span>The Photo Gallery<small>SUPER ADMIN</small></span></a><a className="text-button" href={session?"/dashboard":"/"}>{session?"Studio workspace →":"Back to home →"}</a></header>{!session?<div className="admin-auth-content"><div className="admin-auth-intro"><p className="eyebrow">PRIVATE ADMIN ACCESS</p><h1>Super Admin</h1><p>Sign in to review studio applications and manage accounts.</p></div>{error&&<div className="public-error">{error}</div>}<section className="panel admin-login"><h2>Sign in</h2><form className="request-form" onSubmit={signIn}><input type="email" autoComplete="username" required placeholder="Email address" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" autoComplete="current-password" required placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary">Sign in</button></form><a className="admin-reset-link" href="/reset-password">Forgot password?</a><small>Access is limited to accounts granted Super Admin permission.</small></section></div>:<div className="admin-content"><p className="eyebrow">SUPER ADMINISTRATION</p><h1>Super Admin dashboard</h1><p className="subhead">Review studio approvals, activity, and account settings.</p><nav className="admin-section-nav" aria-label="Super Admin sections"><button type="button" aria-pressed={activeSection==="overview"} onClick={()=>{setActiveSection("overview");window.history.replaceState(null,"","#overview");}}>Overview</button><button type="button" aria-pressed={activeSection==="studio-approvals"} onClick={()=>{setActiveSection("studio-approvals");window.history.replaceState(null,"","#studio-approvals");}}>Studio approvals <span className="admin-nav-count">{studios.length}</span></button><button type="button" aria-pressed={activeSection==="studio-accounts"} onClick={()=>{setActiveSection("studio-accounts");window.history.replaceState(null,"","#studio-accounts");}}>Studio accounts <span className="admin-nav-count">{organizations.length}</span></button></nav>{error&&<div className="public-error">{error}</div>}{message&&<div className="notice">{message}</div>}{error?<div className="panel public-empty">Admin dashboard data is unavailable until access is restored.</div>:<>
 {activeSection==="overview"&&<section className="admin-overview" id="overview"><div className="panel-head"><div><h2>Platform overview</h2><p>Current account, workflow, billing and service health at a glance.</p></div><span className="status status-green"><i/>{overview?.health.api||"Checking"} · API</span></div>{loading&&!overview?<div className="panel public-empty">Loading platform activity…</div>:overview&&<><div className="admin-stat-grid">{[["STUDIOS",overview.summary.studios],["CUSTOMERS",overview.summary.customers],["PROJECTS",overview.summary.projects],["PAYMENTS",overview.summary.payments],["CAPTURED",overview.summary.capturedPayments]].map(([label,value])=><article className="panel admin-stat" key={label}><small>{label}</small><b>{value}</b></article>)}</div><div className="admin-health"><span><i/>API service · {overview.health.api}</span><span><i/>Database queries · {overview.health.database}</span><button className="text-button" onClick={()=>void load()}>Refresh platform data</button></div><div className="admin-data-grid">
  <details className="panel admin-data-card"><summary className="admin-data-summary"><h3>Recent projects</h3><span>{overview.projects.length} records</span></summary>{overview.projects.length?overview.projects.map(p=><div className="admin-data-row" key={p.id}><span><b>{p.name}</b><small>{p.organizations?.name||"Studio"} · {p.clients?.name||"Client"}</small></span><span>{p.status.replaceAll("_"," ")}<small>{money(p.amount_paid)} / {money(p.total_amount)} paid</small></span></div>):<p>No projects yet.</p>}</details>
  <details className="panel admin-data-card"><summary className="admin-data-summary"><h3>Recent customers</h3><span>{overview.customers.length} records</span></summary>{overview.customers.length?overview.customers.map(c=><div className="admin-data-row" key={c.id}><span><b>{c.name}</b><small>{c.email||"No email"}</small></span><span>{c.organizations?.name||"Studio"}<small>{new Date(c.created_at).toLocaleDateString()}</small></span></div>):<p>No customer records yet.</p>}</details>
  <details className="panel admin-data-card"><summary className="admin-data-summary"><h3>Recent payments</h3><span>{overview.payments.length} records</span></summary>{overview.payments.length?overview.payments.map(p=><div className="admin-data-row" key={p.id}><span><b>{money(p.amount)} {p.currency}</b><small>{p.projects?.name||"Project"} · {p.organizations?.name||"Studio"}</small></span><span className={`status ${p.status==="CAPTURED"?"status-green":p.status==="FAILED"?"status-amber":"status-blue"}`}><i/>{p.status.replaceAll("_"," ")}</span></div>):<p>No payment attempts yet.</p>}</details>
  <details className="panel admin-data-card"><summary className="admin-data-summary"><h3>Subscriptions</h3><span>{overview.subscriptions.length} accounts</span></summary>{overview.subscriptions.length?overview.subscriptions.map(s=><div className="admin-data-row" key={s.organization_id}><span><b>{s.organizations?.name||"Studio"}</b><small>Plan account</small></span><span>{s.status.replaceAll("_"," ")}<small>{s.current_period_end?new Date(s.current_period_end).toLocaleDateString():"No end date set"}</small></span></div>):<p>No subscription records yet.</p>}</details>
 </div></>}</section>}
 {activeSection==="studio-approvals"&&<section className="admin-section" id="studio-approvals"><div className="panel-head"><div><h2>Studio approvals</h2><p>Review new studio registrations before they can publish.</p></div></div>{studios.length===0?<div className="panel public-empty">No studios are waiting for review.</div>:<div className="admin-list">{studios.map(s=><article className="panel review-card" key={s.id}><div><span className="status status-amber"><i/>Pending review</span><h2>{s.name}</h2><p>Submitted {new Date(s.created_at).toLocaleDateString()} · {s.organization_members?.length||0} member(s)</p>{s.review_note&&<p>{s.review_note}</p>}</div><div className="review-actions"><button className="secondary-button" onClick={()=>void decision(s.id,"REJECT")}>Decline</button><button className="primary" onClick={()=>void decision(s.id,"APPROVE")}>Approve studio</button></div></article>)}</div>}</section>}
 {activeSection==="studio-accounts"&&<section className="admin-operations" id="studio-accounts">
  <div className="panel-head"><div><h2>Studio accounts</h2><p>Manage status and storage limits.</p></div><span className="admin-section-count">{organizations.length} studios</span></div>
  {!storageAddonsAvailable&&<p className="notice" role="status">Storage add-on history is unavailable until migration 011_storage_billing.sql is applied. Studio accounts and current quotas are still available.</p>}
  {organizations.length===0?<div className="panel public-empty">No studio accounts found.</div>:<div className="admin-org-list">
    <div className="admin-org-table-head"><span>Studio</span><span>Storage used</span><span>Storage limit</span><span>Account</span></div>
    {organizations.map(o=>{const used=o.storage_used_bytes+o.storage_reserved_bytes;const pct=o.storage_limit_bytes?Math.min(100,used/o.storage_limit_bytes*100):0;return <article className="admin-org-row" key={o.id}>
      <div className="admin-org-identity"><strong>{o.name}</strong><small>Created {new Date(o.created_at).toLocaleDateString()}</small><small>{o.subscription?.plan_name||"Basic"} plan · {o.subscription?.status?.replaceAll("_"," ")||"PENDING PAYMENT"}{o.subscription?.current_period_end?` · renews ${new Date(o.subscription.current_period_end).toLocaleDateString()}`:""}</small><small>{o.storageAddons?.count||0} add-ons · {bytes(o.storageAddons?.bytes||0)} added · {money(o.storageAddons?.amount||0)} paid</small></div>
      <div className="admin-org-usage"><div className="admin-usage-meter"><i style={{width:`${pct}%`}}/></div><span>{bytes(used)} <small>· {pct.toFixed(0)}%</small></span></div>
      <div className="admin-org-limit"><label><input aria-label={`Storage limit for ${o.name} in GiB`} type="number" min="0" max="5242880" step="1" value={limits[o.id]??""} onChange={e=>setLimits(v=>({...v,[o.id]:e.target.value}))}/><span>GiB</span></label><button className="text-button" disabled={busy===o.id||limits[o.id]==null||!Number.isFinite(Number(limits[o.id]))||Number(limits[o.id])<0} onClick={()=>void updateStudio(o,{storageLimitBytes:Math.round(Number(limits[o.id])*1024**3)})}>{busy===o.id?"Saving…":"Save"}</button></div>
      <div className="admin-org-actions"><span className={`status ${o.status==="ACTIVE"?"status-green":o.status==="SUSPENDED"?"status-amber":"status-blue"}`}><i/>{o.status.replaceAll("_"," ")}</span><button className={o.status==="ACTIVE"?"secondary-button":"primary"} disabled={busy===o.id||o.status==="PENDING_APPROVAL"} onClick={()=>void updateStudio(o,{status:o.status==="ACTIVE"?"SUSPENDED":"ACTIVE"})}>{o.status==="ACTIVE"?"Suspend":"Activate"}</button></div>
    </article>})}
  </div>}
</section>}</>}</div>}</main>
}
