import * as tus from "tus-js-client";
export type UploadAuth={apiBase:string;accessToken:string;organizationId:string};
export type UploadProgress=(sentBytes:number,totalBytes:number)=>void;
export type ImageVariant="preview"|"thumbnail";
export type Derivatives={preview:File;thumbnail:File;width:number;height:number};
async function api<T>(auth:UploadAuth,path:string,init:RequestInit={}):Promise<T>{const response=await fetch(`${auth.apiBase.replace(/\/$/,"")}${path}`,{...init,headers:{Authorization:`Bearer ${auth.accessToken}`,"x-organization-id":auth.organizationId,...(init.body?{"Content-Type":"application/json"}:{}),...init.headers}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Upload request failed.");return body as T;}
export async function uploadPhotoOrFile(auth:UploadAuth,projectId:string,file:File,progress:UploadProgress,signal?:AbortSignal,resumeUploadId?:string,onSession?:(uploadId:string)=>void,target?:{mediaId?:string;variant?:ImageVariant;width?:number;height?:number}):Promise<string>{
 type Session={uploadId:string;partSizeBytes:number;partCount:number;parts?:{partNumber:number;etag:string;sizeBytes:number}[]};
 const create=()=>api<Session>(auth,"/uploads/r2",{method:"POST",body:JSON.stringify({projectId,filename:file.name,mimeType:file.type||"application/octet-stream",sizeBytes:file.size,...target})});
 return uploadPhotoOrFileAttempt(auth,projectId,file,progress,signal,resumeUploadId,onSession,create,0);
}

async function uploadPhotoOrFileAttempt(auth:UploadAuth,projectId:string,file:File,progress:UploadProgress,signal:AbortSignal|undefined,resumeUploadId:string|undefined,onSession:((uploadId:string)=>void)|undefined,create:()=>Promise<{uploadId:string;partSizeBytes:number;partCount:number;parts?:{partNumber:number;etag:string;sizeBytes:number}[]}>,recoveryAttempt:number):Promise<string>{
 let resumed=!!resumeUploadId;let session:Awaited<ReturnType<typeof create>>;
 if(resumeUploadId){try{session=await api<Awaited<ReturnType<typeof create>>>(auth,`/uploads/${resumeUploadId}`);}catch(error){const message=error instanceof Error?error.message.toLowerCase():"";if(!message.includes("upload session not found")&&!message.includes("expired or unavailable"))throw error;resumed=false;session=await create();}}else session=await create();
 const uploadId=session.uploadId;onSession?.(uploadId);const existing=resumed?session.parts||[]:[];const completed=new Map<number,string>(existing.map(x=>[x.partNumber,x.etag]));let sent=existing.reduce((sum,x)=>sum+x.sizeBytes,0);progress(sent,file.size);const pending=Array.from({length:session.partCount},(_,i)=>i+1).filter(n=>!completed.has(n));let cursor=0;
 try{const workers=Array.from({length:Math.min(3,pending.length)},async()=>{while(cursor<pending.length){if(signal?.aborted)throw new DOMException("Upload cancelled","AbortError");const partNumber=pending[cursor++];const {url}=await api<{url:string}>(auth,`/uploads/${uploadId}/parts`,{method:"POST",body:JSON.stringify({partNumber})});const start=(partNumber-1)*session.partSizeBytes;const part=file.slice(start,Math.min(start+session.partSizeBytes,file.size));const response=await fetch(url,{method:"PUT",body:part,signal});const etag=response.headers.get("ETag");if(!response.ok||!etag)throw new Error(`Part ${partNumber} failed. Retry to continue this upload.`);completed.set(partNumber,etag);sent+=part.size;progress(sent,file.size);}});const workerErrors:unknown[]=[];await Promise.all(workers.map(worker=>worker.catch(error=>{workerErrors.push(error)})));if(workerErrors.length)throw workerErrors[0];const result=await api<{mediaId:string}>(auth,`/uploads/${uploadId}/complete`,{method:"POST",body:JSON.stringify({parts:[...completed].map(([PartNumber,ETag])=>({PartNumber,ETag}))})});return result.mediaId;
 }catch(error){const message=error instanceof Error?error.message.toLowerCase():"";if(recoveryAttempt===0&&message.includes("upload session not found")&&!signal?.aborted){await api<{ok:boolean}>(auth,`/uploads/${uploadId}/abort`,{method:"POST"}).catch(()=>{});progress(0,file.size);return uploadPhotoOrFileAttempt(auth,projectId,file,progress,signal,undefined,onSession,create,recoveryAttempt+1);}throw error;}
}
export async function uploadVideo(auth:UploadAuth,projectId:string,file:File,progress:UploadProgress,onComplete:(mediaId:string)=>void,onError:(error:Error)=>void,onSession?:(uploadId:string)=>void,resumeUploadId?:string):Promise<tus.Upload>{const session=resumeUploadId?await api<{uploadId:string;uploadUrl:string;sizeBytes:number}>(auth,`/uploads/${resumeUploadId}/resume`):{...await api<{uploadId:string;uploadUrl:string;chunkSizeBytes:number}>(auth,"/uploads/stream",{method:"POST",body:JSON.stringify({projectId,filename:file.name,mimeType:file.type||"video/mp4",sizeBytes:file.size})}),sizeBytes:file.size};if(resumeUploadId&&session.sizeBytes!==file.size)throw new Error("Choose the same video file that was originally selected.");onSession?.(session.uploadId);const upload=new tus.Upload(file,{uploadUrl:session.uploadUrl,chunkSize:50*1024*1024,retryDelays:[0,1000,3000,5000,10000],onProgress(sent,total){progress(sent,total);},onError(error){onError(error);},onSuccess(){void api<{mediaId:string}>(auth,`/uploads/${session.uploadId}/stream/complete`,{method:"POST"}).then(result=>onComplete(result.mediaId)).catch(onError);}});upload.start();return upload;}
async function makeVariant(bitmap:ImageBitmap,source:File,longEdge:number,quality:number,watermark:boolean):Promise<File>{const scale=Math.min(1,longEdge/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Image processing is unavailable in this browser.");ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);if(watermark){const font=Math.max(13,Math.round(canvas.width*.018));ctx.font=`600 ${font}px Arial`;ctx.textAlign="right";ctx.textBaseline="bottom";ctx.fillStyle="rgba(255,255,255,.55)";ctx.shadowColor="rgba(0,0,0,.35)";ctx.shadowBlur=2;ctx.fillText("PREVIEW",canvas.width-14,canvas.height-12);}const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("Could not process image.")),"image/jpeg",quality));const name=source.name.replace(/\.[^.]+$/,""),suffix=longEdge<=500?"thumbnail":"preview";return new File([blob],`${name}-${suffix}.jpg`,{type:"image/jpeg"});}
export async function createPhotoDerivatives(file:File):Promise<Derivatives|null>{if(!file.type.startsWith("image/")||["image/gif","image/svg+xml"].includes(file.type))return null;const bitmap=await createImageBitmap(file);try{const [preview,thumbnail]=await Promise.all([makeVariant(bitmap,file,1800,.78,true),makeVariant(bitmap,file,420,.72,true)]);return {preview,thumbnail,width:bitmap.width,height:bitmap.height};}finally{bitmap.close();}}